name: My Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          gradle clean build
          gradle jacocoTestReport
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/jacoco

  checkstyle:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: config/checkstyle/checkstyle.xml
          workdir: src

  coverage:
    needs: build
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage report
        uses: actions/download-artifact@v2

      - name: Load coverage report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: build/jacoco
          token: ${{ secrets.GITHUB_TOKEN }}
          title: homework
          update-comment: true