name: My Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: gradle clean build

      - name: Collect coverage
        run: gradle test jacocoTestReport

      - name: Copy coverage report
        run: cp -r build/reports/jacoco/test ${{ github.workspace }}

  checkstyle:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: config/checkstyle/checkstyle.xml
          workdir: src

  coverage:
    needs: build
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Collect coverage from build
        run: gradle jacocoTestReport

      - name: Copy coverage report
        run: cp -r build/jacoco ${{ github.workspace }}

      - name: Upload coverage report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: homework
          update-comment: true